formatter: markdown
header-from: main.tf
sort:
  enabled: false
settings:
  html: false

recursive:
  path: modules

output:
  file: README.md
  mode: inject

sections:
  show:
    - providers
    - inputs
    - outputs